# https://kubernetes.io/docs/concepts/workloads/pods/downward-api/

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seal-storage
  name: seal-storage-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: seal-storage
  template:
    metadata:
      labels:
        app: seal-storage
    spec:
      containers:
      - image: btoll/seal-storage:0.1.0
        name: seal-storage
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
#          - name: POD_IP_DUAL_STACK
#            valueFrom:
#              fieldRef:
#                fieldPath: status.podIPs

